############################## INFORMATION ##############################
# When starting either Genome Skimmong workflows or Metagenomics workflows
# Can select the workflow by defining the 'pipeline' variable
# 
# COMMANDS
# BAR: 
# snakemake --use-conda --use-singularity --singularity-args "-B /home/genomics/gleberre/01_Research_BAR_ZAND/01_BAR/01_BAR_GS:/home/genomics/gleberre/01_Research_BAR_ZAND/03_Pipeline_development/mnt" --cores 24
# ZAND: 
# snakemake --use-conda --use-singularity --singularity-args "-B /home/genomics/gleberre/01_Research_BAR_ZAND/02_ZAND/01_ZAND_GS:/home/genomics/gleberre/01_Research_BAR_ZAND/03_Pipeline_development/mnt" --cores 24

pipeline: "Genome_Skimming" 
# Genome_Skimming
# Metagenomics

genome_skimming:
  sample: 'MB_GS_N_latericeus_S41'
  
  seqdata: "00_ZAND_RAW_SEQ/01_SEQ_GS"
  # BAR_GS: "00_BAR_RAW_SEQ/01_SEQ_GS"
  # ZAND_GS: "00_ZAND_RAW_SEQ/01_SEQ_GS"

  project: "01_ZAND_GS"
  # BAR_GS: "01_BAR_GS"
  # ZAND_GS: "01_ZAND_GS"
  
  datadir: "/home/genomics/gleberre/01_Research_BAR_ZAND/02_ZAND/" 
  # BAR: "/home/genomics/gleberre/01_Research_BAR_ZAND/01_BAR/" 
  # ZAND: "/home/genomics/gleberre/01_Research_BAR_ZAND/02_ZAND/"

  dockerdir: "/home/genomics/gleberre/01_Research_BAR_ZAND/03_Pipeline_development/mnt"
  # The directory used when docker/singularity is initialized 

  KrakenStand: "/home/genomics/gleberre/01_Research_BAR_ZAND/03_Pipeline_development/databases/K2_Standard_DB/"
  # Path to the Kraken Standard database for contamination filtering. 

  workflow: "AssemblyFree" 
  # Assembly: To perform the Assemblies of mtDNA, rDNA and Nuclear DNA. 
  # AssemblyFree: Perfrom the k-mer matching of the Genome Skim reads using KRAKEN2
  # KrakenBuildDB: Build a custom KRAKEN2 database from all gathered reads after Aseembly Free
  # AssemblyFree_KrakenBuild: The complete pipeline to perfrom k-mer matching of the reads, followed by the creation of a custom database. 
  # AllAssemblies: Perfrom the Assembly methods for mtDNA, rDNA and Nuclear DNA togheter with the k-mer matching og the GenomeSkim reads.
  # AllAssemblies_KrakenBuild: Perfrom the Assembly methods for mtDNA, rDNA and Nuclear DNA togheter with the k-mer matching og the GenomeSkim reads. Finalized with the creation of the GenomeSkim database with KRAKEN2. 
  
  species: "Notomastus_latericeus"

  taxid: "167831" 
  # Need to add the Taxonomic ID when performing Assembly Free Analysis
  # Pplatessa: 8262
  # Sscombrus: 13677
  # Charengus: 7950
  # Abra alba: 399303
  # Macoma balthica: 1903275
  # Nepthys cirrosa: 714606
  # Fabulina fabula: 2589387
  # Glycera alba: 221998
  # Magelona johnstoni: 1436028
  # Nephtys caeca: 714603
  # Ophuria ophuria: 72673
  # Nephtys hombergii: 36121
  # Owenia fusiformis: 6347
  # Eumida sanguinea: 329452
  # Nephtys longosetosa: 397560
  # Notomastus latericeus: 167831

  KrakenDB: "MacrobenthosDB"
  # Name of the KRAKEN2 Database 

# For the Annotation by MITOS. >> NCBI codon table
mitos:
  database: "/home/genomics/gleberre/01_Research_BAR_ZAND/03_Pipeline_development"
  # 5 == Invertebrate, 2 == Vertebrate, 4 == Mold, 14 Alternative flatworm, 9 == Echinoderm, 13 == Ascidian
  gencode: 5


# Only need to full in performing: Assembly, AllAssemblies, AllAssemblies_KrakenBuild
genbank:
  ## HEADER
  locus_mt: "Notomastus_latericeus_mtDNA"
  locus_rdna: "Notomastus_latericeus_rDNA"

  bioproject_mt: "Mitochondrial_Assembly"
  bioproject_rdna: "Ribosomal_Assembly"

  sample_type: "ILVO - RMG"
  taxonomy: "Notomastus_latericeus"
  organism_header: "Notomastus latericeus"
  mol_type: "DNA"

  ## FEATURE TABLE
  # SOURCE
  organism: "Notomastus_latericeus"

## METAGENOMICS
metagenomics:
  
  sample: 'BAR_MG_Field_3_S28'
  
  workflow: "Gamma_Delta"
  # Kmer_Matching: To perform k-mer matching of the reads against a "Custom" created database
  # Gamma_Delta: Perform the mapping of reads against reference mitochondrial organelle and ribosomal repeats
  # Gamma_Delta_Kmer: Will do both the mapping as well as the matching of the reads
  
  seqdata: "00_BAR_RAW_SEQ/02_SEQ_MG"
  # BAR_MG: "00_BAR_RAW_SEQ/02_SEQ_MG"
  # ZAND_MG: "00_ZAND_RAW_SEQ/02_SEQ_MG"

  project: "02_BAR_MG"
  # BAR_MG: "02_BAR_MG"
  # ZAND_MG: "02_ZAND_MG"
  
  datadir: "/home/genomics/gleberre/01_Research_BAR_ZAND/01_BAR/" 
  # BAR: "/home/genomics/gleberre/01_Research_BAR_ZAND/01_BAR/" 
  # ZAND: "/home/genomics/gleberre/01_Research_BAR_ZAND/02_ZAND/"

  dockerdir: "/home/genomics/gleberre/01_Research_BAR_ZAND/03_Pipeline_development/mnt"
  # The directory used when docker/singularity is initialized 

  KrakenStand: "/home/genomics/gleberre/01_Research_BAR_ZAND/03_Pipeline_development/databases/K2_Standard_DB/"
  # Location to the KRAKEN Standard database for contamination filtering

  KrakenCustomDB: "/home/genomics/gleberre/01_Research_BAR_ZAND/01_BAR/01_BAR_GS/15_Kraken_Databases/GenomeSkimDB"
  # Path to the (Custom) Kraken database for matching the reads against

  FolderReferenceFasta: "/home/genomics/gleberre/01_Research_BAR_ZAND/01_BAR/01_BAR_GS/17_Reference_Mapping_MG"
  # BAR: "/home/genomics/gleberre/01_Research_BAR_ZAND/01_BAR/01_BAR_GS/17_Reference_Mapping_MG" 
  # ZAND: "/home/genomics/gleberre/01_Research_BAR_ZAND/02_ZAND/01_BAR_GS/17_Reference_Mapping_MG"